### ISSUE TITLE
模型无法加载 报错Cannot read properties of undefined (reading 'getMaterialType') 大佬能帮忙看一眼么

### ISSUE THREAD

**Issue by bafenbao** [yangyanggu/layer-3dtiles#5]
TilesRendererBase.js:501  TilesRenderer : Failed to load tile at url "http://gisbg.scyttx.com.cn/gisdata/9171/0/17_207411_41205_0.b3dm".
errorCallback @ TilesRendererBase.js:501
Promise.catch(异步)
requestTileContents @ TilesRendererBase.js:635
recursivelyLoadTiles @ traverseFunctions.js:84
recursivelyLoadTiles @ traverseFunctions.js:78
skipTraversal @ traverseFunctions.js:365
skipTraversal @ traverseFunctions.js:378
skipTraversal @ traverseFunctions.js:378
update @ TilesRendererBase.js:166
update @ TilesRenderer.js:415
update @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
requestAnimationFrame(异步)
animate @ CesiumIonTilesRenderer.js:81
(anonymous) @ CesiumIonTilesRenderer.js:81
Show 73 more frames
显示简略信息
TilesRendererBase.js:502  TypeError: Cannot read properties of undefined (reading 'getMaterialType')
    at GLTFParser.loadMaterial (GLTFLoader.js:3313:32)
    at GLTFLoader.js:2707:38
    at GLTFParser._invokeOne (GLTFLoader.js:2628:19)
    at GLTFParser.getDependency (GLTFLoader.js:2705:24)
    at GLTFParser.loadMesh (GLTFLoader.js:3569:12)
    at GLTFLoader.js:2683:34
    at GLTFParser._invokeOne (GLTFLoader.js:2628:19)
    at GLTFParser.getDependency (GLTFLoader.js:2681:24)
    at GLTFParser.createNodeMesh (GLTFLoader.js:3936:17)
    at GLTFLoader.js:3985:38

**Comment by bafenbao** [comment]
3dtiles json文件为http://gisbg.scyttx.com.cn/gisdata/9171/tileset.json
